""" Laboratorio de computacion guia 3 act1 """
print("--------------------")
print("Dr.Pedro Fernandez🩺️👨‍⚕️")
print("Medico familiar👥👥")
print("2/09/23")
print("direccion cualquiera 123")
print("--------------------")
#creacion de variables
paciente1 = (input("ingrese su nombre💁: "))
fechaNacimiento = (input("Ingrese su fecha de nacimiento: "))
medicamento1 = (input("""Medicamento recetado💊🤒: """))
dosismedic = (input("Dosis recetada🤧🤧: "))
instrucmedic = (input("Instrucciones de uso💬💬: "))
horacons = (input("Dia y Horario de la consulta🤝🤝: "))
estudiossolic = (input("Estudios recetados: "))
proximoturno = (input("Fecha y horario proximo turno🔜🔜: "))


print("Paciente: ")
print("_____________")
(print(paciente1))
print("_____________")
(print(fechaNacimiento))
print("_____________")
print(estudiossolic)
print("_____________")
(print(medicamento1))
print("_____________")
(print(dosismedic))
print("_____________")
(print(instrucmedic))
print("_____________")
print(horacons)
print("_____________")
print("")
print(proximoturno)
print("_____________")