print("-🔴-🔴-🔴-🔴-🔴-🔴-🔴-🔴-🔴-🔴-")
print(         "      CLÍNICA VM SALUD")
print("-🔴-🔴-🔴-🔴-🔴-🔴-🔴-🔴-🔴-🔴-")
#defino una funcion para imprimir los datos de la receta
def imprimirDatosReceta(direccion,doctor,nombre,fecha,medicamento,dosis,instrucciones, nombre2,proxturno,horaproxturno):
    print(direccion)
    print(doctor)
    print(nombre)
    print(fecha)
    print(medicamento)
    print(dosis)
    print(instrucciones)
    print(nombre2)
    print(proxturno)
    print(horaproxturno)

#parte del codigo donde ingreso los datos
direccion = input("🏥Ingrese dirección de la clínica:")
doctor = input("👩🏻‍🔬Ingrese el nombre del doctor/a:")
print("\n -------------------------------------------------")
nombre =input("👧🏻👦🏻Ingrese el nombre del paciente:")
fecha= input("📆Ingrese fecha de nacimiento del paciente:")
print("\n -------------------------------------------------")
medicamento = input("💊Ingrese el medicamento recetado:")
dosis =input("💊Ingrese la dosis recetada:")
instrucciones = input("⏰Ingrese instroducciones del uso del medicamento:")
print("\n -------------------------------------------------")
print("PROXIMO TURNO")
nombre2 = input("Ingrese nombre del paciente:")
proxturno = input("Ingrese el día del turno:")
horaproxturno = input("Ingrese la hora del turno:")
print("\n -------------------------------------------------")
imprimirDatosReceta(direccion,doctor,nombre,fecha,medicamento,dosis,instrucciones, nombre2,proxturno,horaproxturno)

