arbitro1 = input("Ingrese el nombre del árbitro 1: ")
arbitro2 = input("Ingrese el nombre del árbitro 2: ")
arbitro3 = input("Ingrese el nombre del árbitro 3: ")
arbitro4 = input("Ingrese el nombre del árbitro 4: ")
cancha = input("Ingrese el nombre de la cancha: ")
fecha = input("ingrese el día y la hora en la que transcurrirá el partido: ")
print("_____________________________")
print("ARBITROS:")
print(arbitro1.title())
print(arbitro2.title())
print(arbitro3.title())
print(arbitro4.title())
print("_____________________________")
print("CANCHA: ")
print(cancha.upper())
print("FECHA: ")
print(fecha.title())
print("_____________________________")