"""CONSULTORIO SAMUEL BENITO UNID N3"""
Nombre = (input("Ingrese su Nombre;"))
Apellido = (input("Ingrese su apellido;"))
fechadeNacimiento = (input("Ingrese su fecha de nacimeinto;"))
Dni = (input("Ingrese su D.N.I;"))
fechayhorarioconsulta = (input("Ingrese su dia y hora de su consulta;"))
estudiosolicit = (input("Estudios solicitados;"))
medicamento = (input("Medicamentos resetados;"))
dosissolicitada = (input("Dosis solicitada;"))
usodelmedicamnto = (input("Instrucciones del medicamento;"))
proximoturno = (input("Fecha y hora del proximo turno;"))
print("\nConsulta Medica")
(print(Nombre))
print("--------------------")
(print(Apellido))
print("--------------------")
(print(fechadeNacimiento))
print("--------------------")
(print(Dni))
print("--------------------")
(print(fechayhorarioconsulta))
print("\nReceta Medica")
(print(estudiosolicit))
print("--------------------")
(print(medicamento))
print("--------------------")
(print(dosissolicitada))
print("--------------------")
(print(usodelmedicamnto))
print("\nProximo turno")
(print(proximoturno))
